spring:
  datasource:
    url: jdbc:postgresql://172.16.219.183:5432/mydb
    username: myuser
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      format-sql: true
server:
  servlet:
    session:
      timeout: 30m


logging:
  level:
    root: INFO
